### ISSUE TITLE
Compatibilité Postgresql

### ISSUE THREAD

**Issue by MatthieuTexier** [ATM-Consulting/dolibarr_module_abricot#117]
Dolibarr est compatible avec Postgresql mais ce module ne l'est pas.
Cordialement.

**Comment by el-dge** [comment]
Tout à fait.
J'ai fait une PR #127  pour améliorer la situation qui c'est **dégradée** : 
Par ex., les champs sont  **désormais** délimités par ` ce qui est rédhibitoire pour PqSQL cf. https://docs.postgresql.fr/11/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
Exemple défaillant avec le module inventory :
``` sql
SELECT `fk_warehouse`,`entity`,`status`,`per_batch`,`date_inventory`,`title`,date_cre,date_maj FROM llx_inventory WHERE rowid=28
```
avant ça fonctionnait... plus maintenant !
Avant = Abricot version 3.0.3
Maintenant = Abricot version 3.1.0

Remarquez que date_cre et date_maj sont ok.
