### ISSUE TITLE
Fatal error in Abricot when converting an Order into an OF

### ISSUE THREAD

**Issue by kupfair** [ATM-Consulting/dolibarr_module_abricot#206]
After preparing and validating an Order (“Commande client“), we change to the OF view, where we want to create OFs (“Créer OFs“). The systems starts working, but the page then blanks due to a fatal error : 

Fatal error: Uncaught Error: Call to a member function query() on null in /home/clients/mypathabcd/sites/erp.mysite.ch/custom/abricot/includes/class/class.pdo.db.php:244 Stack trace: #0 /home/clients/mypathabcd/sites/erp.mysite.ch/custom/abricot/includes/class/class.pdo.db.php(127): TPDOdb->Execute('SET sql_mode = ...') #1 /home/clients/mypathabcd/sites/erp.mysite.ch/custom/nomenclature/core/triggers/interface_50_modnomenclature_nomenclaturetrigger.class.php(124): TPDOdb->__construct() #2 /home/clients/mypathabcd/sites/erp.mysite.ch/core/class/interfaces.class.php(191): Interfacenomenclaturetrigger->run_trigger('ASSET_LINE_OF_S...', Object(TAssetOFLine), Object(User), Object(Translate), Object(Conf)) #3 /home/clients/mypathabcd/sites/erp.mysite.ch/custom/of/class/ordre_fabrication_asset.class.php(3813): Interfaces->run_triggers('ASSET_LINE_OF_S...', Object(TAssetOFLine), Object(User), Object(Translate), Objec in /home/clients/mypathabcd/sites/erp.mysite.ch/custom/abricot/includes/class/class.pdo.db.php on line 244

Our config:
- Dolibarr 18.0.5
- PHP 7.4.33

The following ATM Modules are installed:
- Abricot 3.8.2
- OF 2.15.0
- Poste de travail 2.1.0
- Nomenclature 4.11.0
- Tasklist 3.1.0
- Commande fournisseur depuis commande client (2.6.6)
- Liste en CSV 1.8.1

Thanks for any hints!

**Comment by atm-john** [comment]
Hi, you are using not compatible modules for Dolibarr 18, I invite you to ATM contact commercial service www.atm-consulting.fr if you need Data migration to new modules packs.

**Comment by kupfair** [comment]
Hello, 
Thank you. Actually, I am rather new to Dolibarr and was using the newest modules from GitHub... 
I contacted ATM a few days ago, and today again – no reply yet...
