### ISSUE TITLE
Lenteur sur liste si on utilise le paramètre d'export

### ISSUE THREAD

**Issue by atm-ph** [ATM-Consulting/dolibarr_module_abricot#23]
La totalité des données de la requête sont traités puis compressés et sérialisés en session pour être envoyés via l'ajout d'une iframe en JS

**Comment by atm-alexis** [comment]
de mémoire c'est pour l'export ça. Donc non nécessaire dans la plupart des cas. On en cause demain

**Comment by atm-alexis** [comment]
Ah merde, je viens de voir le titre. On y reflechira demain quand même ;)
