### ISSUE TITLE
Uniformisation de nos retours ajax

### ISSUE THREAD

**Issue by aconits** [ATM-Consulting/dolibarr_module_abricot#28]
J'étais en train de coder et je me suis posé la question "comment je traite mon retour ajax de interface.php"
Je commence à créer une petite class (potentiel sur-qualité) avec quelques attributs comme $error, $errors, $success et $data
Puis à chaque appel ajax je m'obligerai à retourner dans 100% des cas un objet de cette class, pour faire soit du traitement d'erreur ou afficher de la données côté client

Est-ce que cette class (par exemple : interfaceResponse) aurait sa place dans abricot ?
Comme on est sensé faire appel à un fichier interface.php si on fait de l'ajax, pourquoi pas uniformiser le retour aussi ?

**Comment by atm-florian** [comment]
Quoi on traite le retour d'erreur ;-) je plusois

**Comment by atm-florianm** [comment]
L'idée est bonne en soi, mais je pense qu'on ne le fera pas dans Abricot.
