### ISSUE TITLE
Declare reverse dependencies

### ISSUE THREAD

**Issue by rdoursenaud** [ATM-Consulting/dolibarr_module_abricot#4]
A bunch of modules can't work without this module.

These should be listed in the requiredby so that reverse dependency works.
I.e.: modules are disabled if this module is disabled.

**Comment by atm-florianm** [comment]
From our experience, declaring abricot as a dependency in all modules that use it has the nasty side-effect of disabling a lot of modules should you disable abricot by accident (which incidentally doesn't need to be enabled).

**Comment by rdoursenaud** [comment]
It is not a module then. It's a library. You shouldn't ship libraries as modules IMHO ;)
Given how old this issue is, I don't remember the context though…
