### ISSUE TITLE
BUG : update for QUERY module ?

### ISSUE THREAD

**Issue by BebZ** [ATM-Consulting/dolibarr_module_abricot#7]
![image](https://cloud.githubusercontent.com/assets/3694135/13257744/58e6480c-da50-11e5-9f8b-d1f83f630f73.png)

![image](https://cloud.githubusercontent.com/assets/3694135/13257719/4c08068e-da50-11e5-8285-239f92548169.png)

**Comment by atm-alexis** [comment]
Hi,

The good version has been packaged in the release tab,

Regars

**Comment by BebZ** [comment]
+10000
